---
apiVersion: v1
kind: Namespace
metadata:
  name: fortune-ns

---
apiVersion: v1 
kind: Pod 
metadata:
  name: fortune-po
  labels:
    dev: chuk 
  namespace: fortune-ns 
spec: 
  containers:
  - name: fortune-container
    image: chukmunnlee/fortune:v2 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000