---
apiVersion: v1
kind: Pod
metadata:
  name: dov-bear-po
  labels:
    developer: chuk
  namespace: myns
spec:
  containers:
  - name: dov-bear-container
    image: chukmunnlee/dov-bear:v4
    imagePullPolicy: IfNotPresent
    ports: 
    - containerPort: 3000
    - containerPort: 3100